CREATE TABLE `Users` (
`id` INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`user_id` VARCHAR(256) NOT NULL,
`root_id` BIGINT(8) UNSIGNED NOT NULL,
`delta_cursor` VARCHAR(1024)
)
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE `Layout` (
`id` BIGINT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`root_id` BIGINT(8) UNSIGNED,
`parent_id` BIGINT(8) UNSIGNED,
`path` VARCHAR(256) NOT NULL,
`file_id` BIGINT(8) UNSIGNED NOT NULL
)
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE `Files` (
`id` BIGINT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`dir` BOOL NOT NULL,
`name` VARCHAR(256) NOT NULL,
`size` BIGINT(8) NOT NULL
)
CHARACTER SET utf8
COLLATE utf8_general_ci;
