CREATE TABLE `Users` (
`id` INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`user_id` VARCHAR(256) NOT NULL,
`root_id` BIGINT(8) UNSIGNED NOT NULL,
`delta_cursor` VARCHAR(256)
);

CREATE TABLE `Layout` (
`id` BIGINT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`root_id` BIGINT(8) UNSIGNED,
`parent_id` BIGINT(8) UNSIGNED,
`path` VARCHAR(256) NOT NULL,
`file_id` BIGINT(8) UNSIGNED NOT NULL
);

CREATE TABLE `Files` (
`id` BIGINT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`hash` VARCHAR(32),
`name` VARCHAR(256) NOT NULL,
`size` BIGINT(8) NOT NULL
);
